version: "3.9"

services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - backend  # Add this line


networks:
  backend:
    driver: bridge
