version: "3.9"

services:
  web:
    build: .
    ports:
      - "8003:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs  # Mount logs directory for persistent logging
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true